using System.Text;
using System.Web;

namespace FluentPDF.Rendering.Interop.Verification.Reports;

/// <summary>
/// Exports validation reports to self-contained HTML format with embedded CSS and color-coded severity levels.
/// </summary>
public class HtmlReportGenerator : IReportExporter<ValidationReport>
{
    /// <summary>
    /// Exports the validation report to an HTML file.
    /// </summary>
    /// <param name="report">The validation report to export.</param>
    /// <param name="outputPath">The file path where the HTML should be saved.</param>
    /// <param name="cancellationToken">Optional cancellation token.</param>
    public async Task ExportAsync(ValidationReport report, string outputPath, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(report);
        ArgumentException.ThrowIfNullOrWhiteSpace(outputPath);

        var directory = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
        {
            Directory.CreateDirectory(directory);
        }

        var html = GenerateHtml(report);

        await File.WriteAllTextAsync(outputPath, html, cancellationToken);
    }

    /// <summary>
    /// Generates complete HTML document from validation report.
    /// </summary>
    private static string GenerateHtml(ValidationReport report)
    {
        var sb = new StringBuilder();

        // HTML header with embedded CSS
        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html lang=\"en\">");
        sb.AppendLine("<head>");
        sb.AppendLine("    <meta charset=\"UTF-8\">");
        sb.AppendLine("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
        sb.AppendLine($"    <title>Marshaling Validation Report - {HttpUtility.HtmlEncode(report.ValidatorName)}</title>");
        sb.AppendLine("    <style>");
        sb.AppendLine(GetEmbeddedCss());
        sb.AppendLine("    </style>");
        sb.AppendLine("</head>");
        sb.AppendLine("<body>");

        // Header
        GenerateHeader(sb, report);

        // Summary section
        GenerateSummary(sb, report);

        // Results by area
        GenerateResultsByArea(sb, report);

        // Footer
        sb.AppendLine("    <footer>");
        sb.AppendLine($"        <p>Generated by FluentPDF Marshaling Verification System on {report.Timestamp:yyyy-MM-dd HH:mm:ss} UTC</p>");
        sb.AppendLine("    </footer>");

        sb.AppendLine("</body>");
        sb.AppendLine("</html>");

        return sb.ToString();
    }

    /// <summary>
    /// Generates the HTML header section.
    /// </summary>
    private static void GenerateHeader(StringBuilder sb, ValidationReport report)
    {
        var statusClass = GetStatusClass(report.Summary.OverallStatus);
        var statusText = report.Summary.OverallStatus.ToString();

        sb.AppendLine("    <header>");
        sb.AppendLine("        <h1>Marshaling Validation Report</h1>");
        sb.AppendLine($"        <div class=\"status-badge {statusClass}\">{HttpUtility.HtmlEncode(statusText)}</div>");
        sb.AppendLine("    </header>");

        sb.AppendLine("    <section class=\"report-info\">");
        sb.AppendLine($"        <div class=\"info-item\"><strong>Validator:</strong> {HttpUtility.HtmlEncode(report.ValidatorName)}</div>");
        sb.AppendLine($"        <div class=\"info-item\"><strong>Target Area:</strong> {HttpUtility.HtmlEncode(report.TargetArea)}</div>");
        sb.AppendLine($"        <div class=\"info-item\"><strong>Timestamp:</strong> {report.Timestamp:yyyy-MM-dd HH:mm:ss} UTC</div>");
        sb.AppendLine("    </section>");
    }

    /// <summary>
    /// Generates the summary statistics section.
    /// </summary>
    private static void GenerateSummary(StringBuilder sb, ValidationReport report)
    {
        sb.AppendLine("    <section class=\"summary\">");
        sb.AppendLine("        <h2>Summary</h2>");
        sb.AppendLine("        <div class=\"summary-grid\">");

        AddSummaryCard(sb, "Total Tests", report.Summary.TotalTests, "neutral");
        AddSummaryCard(sb, "Passed", report.Summary.PassedCount, "success");
        AddSummaryCard(sb, "Failed", report.Summary.FailedCount, report.Summary.FailedCount > 0 ? "error" : "neutral");
        AddSummaryCard(sb, "Warnings", report.Summary.WarningCount, report.Summary.WarningCount > 0 ? "warning" : "neutral");
        AddSummaryCard(sb, "Critical", report.Summary.CriticalCount, report.Summary.CriticalCount > 0 ? "critical" : "neutral");
        AddSummaryCard(sb, "Pass Rate", $"{report.Summary.PassPercentage:F1}%",
            report.Summary.PassPercentage >= 100 ? "success" :
            report.Summary.PassPercentage >= 80 ? "warning" : "error");

        sb.AppendLine("        </div>");
        sb.AppendLine("    </section>");
    }

    /// <summary>
    /// Adds a summary card to the grid.
    /// </summary>
    private static void AddSummaryCard(StringBuilder sb, string label, object value, string type)
    {
        sb.AppendLine($"        <div class=\"summary-card {type}\">");
        sb.AppendLine($"            <div class=\"card-label\">{HttpUtility.HtmlEncode(label)}</div>");
        sb.AppendLine($"            <div class=\"card-value\">{HttpUtility.HtmlEncode(value.ToString())}</div>");
        sb.AppendLine("        </div>");
    }

    /// <summary>
    /// Generates the results by area section.
    /// </summary>
    private static void GenerateResultsByArea(StringBuilder sb, ValidationReport report)
    {
        sb.AppendLine("    <section class=\"results\">");
        sb.AppendLine("        <h2>Validation Results by Area</h2>");

        foreach (var (area, results) in report.ResultsByArea.OrderBy(x => x.Key))
        {
            sb.AppendLine($"        <div class=\"area-section\">");
            sb.AppendLine($"            <h3>{HttpUtility.HtmlEncode(area)}</h3>");
            sb.AppendLine("            <table class=\"results-table\">");
            sb.AppendLine("                <thead>");
            sb.AppendLine("                    <tr>");
            sb.AppendLine("                        <th>Test Name</th>");
            sb.AppendLine("                        <th>Status</th>");
            sb.AppendLine("                        <th>Severity</th>");
            sb.AppendLine("                        <th>Details</th>");
            sb.AppendLine("                    </tr>");
            sb.AppendLine("                </thead>");
            sb.AppendLine("                <tbody>");

            foreach (var result in results)
            {
                GenerateResultRow(sb, result);
            }

            sb.AppendLine("                </tbody>");
            sb.AppendLine("            </table>");
            sb.AppendLine("        </div>");
        }

        sb.AppendLine("    </section>");
    }

    /// <summary>
    /// Generates a table row for a validation result.
    /// </summary>
    private static void GenerateResultRow(StringBuilder sb, ValidationResult result)
    {
        var statusClass = result.Passed ? "status-pass" : "status-fail";
        var statusIcon = result.Passed ? "✓" : "✗";
        var severityClass = GetSeverityClass(result.Severity);

        sb.AppendLine("                    <tr>");
        sb.AppendLine($"                        <td>{HttpUtility.HtmlEncode(result.TestName)}</td>");
        sb.AppendLine($"                        <td class=\"{statusClass}\">{statusIcon}</td>");
        sb.AppendLine($"                        <td class=\"{severityClass}\">{HttpUtility.HtmlEncode(result.Severity.ToString())}</td>");
        sb.AppendLine("                        <td>");

        // Message
        if (!string.IsNullOrEmpty(result.Message))
        {
            sb.AppendLine($"                            <div class=\"detail-message\">{HttpUtility.HtmlEncode(result.Message)}</div>");
        }

        // Error details
        if (!string.IsNullOrEmpty(result.ErrorDetails))
        {
            sb.AppendLine($"                            <div class=\"detail-error\"><strong>Error:</strong> {HttpUtility.HtmlEncode(result.ErrorDetails)}</div>");
        }

        // Expected vs Actual
        if (result.ExpectedValue != null || result.ActualValue != null)
        {
            sb.AppendLine("                            <div class=\"detail-comparison\">");
            if (result.ExpectedValue != null)
            {
                sb.AppendLine($"                                <div><strong>Expected:</strong> {HttpUtility.HtmlEncode(result.ExpectedValue.ToString())}</div>");
            }
            if (result.ActualValue != null)
            {
                sb.AppendLine($"                                <div><strong>Actual:</strong> {HttpUtility.HtmlEncode(result.ActualValue.ToString())}</div>");
            }
            sb.AppendLine("                            </div>");
        }

        // Suggested fix
        if (!string.IsNullOrEmpty(result.SuggestedFix))
        {
            sb.AppendLine($"                            <div class=\"detail-fix\"><strong>Suggested Fix:</strong> {HttpUtility.HtmlEncode(result.SuggestedFix)}</div>");
        }

        // Documentation URL
        if (!string.IsNullOrEmpty(result.DocumentationUrl))
        {
            sb.AppendLine($"                            <div class=\"detail-doc\"><strong>Documentation:</strong> <a href=\"{HttpUtility.HtmlAttributeEncode(result.DocumentationUrl)}\" target=\"_blank\">{HttpUtility.HtmlEncode(result.DocumentationUrl)}</a></div>");
        }

        // Context
        if (result.Context != null && result.Context.Count > 0)
        {
            sb.AppendLine("                            <div class=\"detail-context\">");
            sb.AppendLine("                                <strong>Context:</strong>");
            sb.AppendLine("                                <ul>");
            foreach (var (key, value) in result.Context)
            {
                sb.AppendLine($"                                    <li><strong>{HttpUtility.HtmlEncode(key)}:</strong> {HttpUtility.HtmlEncode(value)}</li>");
            }
            sb.AppendLine("                                </ul>");
            sb.AppendLine("                            </div>");
        }

        sb.AppendLine("                        </td>");
        sb.AppendLine("                    </tr>");
    }

    /// <summary>
    /// Gets the CSS class for a validation status.
    /// </summary>
    private static string GetStatusClass(ValidationStatus status)
    {
        return status switch
        {
            ValidationStatus.Passed => "status-passed",
            ValidationStatus.Warning => "status-warning",
            ValidationStatus.Failed => "status-failed",
            ValidationStatus.Critical => "status-critical",
            _ => "status-unknown"
        };
    }

    /// <summary>
    /// Gets the CSS class for a severity level.
    /// </summary>
    private static string GetSeverityClass(ValidationSeverity severity)
    {
        return severity switch
        {
            ValidationSeverity.Info => "severity-info",
            ValidationSeverity.Warning => "severity-warning",
            ValidationSeverity.Error => "severity-error",
            ValidationSeverity.Critical => "severity-critical",
            _ => "severity-unknown"
        };
    }

    /// <summary>
    /// Gets the embedded CSS for the HTML report.
    /// </summary>
    private static string GetEmbeddedCss()
    {
        return @"
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f5f5f5;
            padding: 20px;
        }

        header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 8px;
            margin-bottom: 20px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        header h1 {
            font-size: 2em;
            font-weight: 600;
        }

        .status-badge {
            padding: 10px 20px;
            border-radius: 20px;
            font-weight: bold;
            font-size: 1.1em;
        }

        .status-passed { background-color: #10b981; color: white; }
        .status-warning { background-color: #f59e0b; color: white; }
        .status-failed { background-color: #ef4444; color: white; }
        .status-critical { background-color: #dc2626; color: white; animation: pulse 2s infinite; }
        .status-unknown { background-color: #6b7280; color: white; }

        @keyframes pulse {
            0%, 100% { opacity: 1; }
            50% { opacity: 0.7; }
        }

        .report-info {
            background: white;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .info-item {
            margin-bottom: 10px;
            font-size: 1.05em;
        }

        .info-item:last-child {
            margin-bottom: 0;
        }

        .summary {
            background: white;
            padding: 30px;
            border-radius: 8px;
            margin-bottom: 20px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .summary h2 {
            margin-bottom: 20px;
            color: #667eea;
        }

        .summary-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 15px;
        }

        .summary-card {
            padding: 20px;
            border-radius: 8px;
            text-align: center;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .summary-card.success { background-color: #d1fae5; border-left: 4px solid #10b981; }
        .summary-card.warning { background-color: #fef3c7; border-left: 4px solid #f59e0b; }
        .summary-card.error { background-color: #fee2e2; border-left: 4px solid #ef4444; }
        .summary-card.critical { background-color: #fecaca; border-left: 4px solid #dc2626; }
        .summary-card.neutral { background-color: #e5e7eb; border-left: 4px solid #6b7280; }

        .card-label {
            font-size: 0.9em;
            color: #6b7280;
            margin-bottom: 8px;
            font-weight: 500;
        }

        .card-value {
            font-size: 1.8em;
            font-weight: bold;
            color: #1f2937;
        }

        .results {
            background: white;
            padding: 30px;
            border-radius: 8px;
            margin-bottom: 20px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .results h2 {
            margin-bottom: 20px;
            color: #667eea;
        }

        .area-section {
            margin-bottom: 30px;
        }

        .area-section h3 {
            color: #374151;
            margin-bottom: 15px;
            padding-bottom: 8px;
            border-bottom: 2px solid #e5e7eb;
        }

        .results-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        .results-table thead {
            background-color: #f9fafb;
        }

        .results-table th {
            padding: 12px;
            text-align: left;
            font-weight: 600;
            color: #374151;
            border-bottom: 2px solid #e5e7eb;
        }

        .results-table td {
            padding: 12px;
            border-bottom: 1px solid #e5e7eb;
            vertical-align: top;
        }

        .results-table tbody tr:hover {
            background-color: #f9fafb;
        }

        .status-pass {
            color: #10b981;
            font-weight: bold;
            font-size: 1.2em;
        }

        .status-fail {
            color: #ef4444;
            font-weight: bold;
            font-size: 1.2em;
        }

        .severity-info { color: #3b82f6; font-weight: 500; }
        .severity-warning { color: #f59e0b; font-weight: 600; }
        .severity-error { color: #ef4444; font-weight: 600; }
        .severity-critical { color: #dc2626; font-weight: bold; }
        .severity-unknown { color: #6b7280; font-weight: 500; }

        .detail-message {
            margin-bottom: 8px;
            color: #4b5563;
        }

        .detail-error {
            margin-top: 8px;
            padding: 8px;
            background-color: #fee2e2;
            border-left: 3px solid #ef4444;
            border-radius: 4px;
            font-size: 0.95em;
        }

        .detail-comparison {
            margin-top: 8px;
            padding: 8px;
            background-color: #fef3c7;
            border-left: 3px solid #f59e0b;
            border-radius: 4px;
            font-size: 0.95em;
        }

        .detail-fix {
            margin-top: 8px;
            padding: 8px;
            background-color: #dbeafe;
            border-left: 3px solid #3b82f6;
            border-radius: 4px;
            font-size: 0.95em;
        }

        .detail-doc {
            margin-top: 8px;
            font-size: 0.95em;
        }

        .detail-doc a {
            color: #3b82f6;
            text-decoration: none;
        }

        .detail-doc a:hover {
            text-decoration: underline;
        }

        .detail-context {
            margin-top: 8px;
            font-size: 0.95em;
        }

        .detail-context ul {
            margin-left: 20px;
            margin-top: 5px;
        }

        .detail-context li {
            margin-bottom: 3px;
        }

        footer {
            text-align: center;
            color: #6b7280;
            padding: 20px;
            margin-top: 20px;
        }

        @media print {
            body {
                background-color: white;
            }

            header {
                background: #667eea;
                print-color-adjust: exact;
                -webkit-print-color-adjust: exact;
            }

            .summary-card, .detail-error, .detail-comparison, .detail-fix {
                print-color-adjust: exact;
                -webkit-print-color-adjust: exact;
            }
        }";
    }
}
