namespace FluentPDF.QualityAgent.Models;

/// <summary>
/// Represents a root cause hypothesis generated by AI analysis.
/// </summary>
public class RootCauseHypothesis
{
    /// <summary>
    /// The issue or problem identified.
    /// </summary>
    public required string Issue { get; init; }

    /// <summary>
    /// The hypothesis about the root cause.
    /// </summary>
    public required string Hypothesis { get; init; }

    /// <summary>
    /// Confidence level (0.0-1.0).
    /// </summary>
    public double Confidence { get; init; }

    /// <summary>
    /// Severity level: Low, Medium, High, Critical.
    /// </summary>
    public required string Severity { get; init; }

    /// <summary>
    /// Recommended actions to resolve the issue.
    /// </summary>
    public List<string> RecommendedActions { get; init; } = new();

    /// <summary>
    /// Related log entries or context.
    /// </summary>
    public List<string> RelatedContext { get; init; } = new();
}

/// <summary>
/// Results from test failure analysis.
/// </summary>
public record TestFailureAnalysis
{
    public required string TestName { get; init; }
    public RootCauseHypothesis? AiHypothesis { get; init; }
    public RootCauseHypothesis? RuleBasedHypothesis { get; init; }
    public bool UsedFallback { get; init; }
    public string? AnalysisError { get; init; }
}
